name: Build and Release

on: 
  push:
    branches:
      - main

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Install Node.js
      uses: actions/setup-node@v2
      with: 
        node-version: 14
    
    - name: Install Electron  
      run: npx electron-builder install-app-deps
    
    - name: Install Dependencies
      run: npm install
    
    - name: Build Application
      run: npm run build

    - env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}  
      run: |
        npx electron-builder --win --linux --publish always
