name: Build and Release

on: 
  push:
    branches:
      - main

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Install Node.js
      uses: actions/setup-node@v2
      with: 
          node-version: 14  
        
    - name: Install and build
      run: |
            npm install
            npm run postinstall
            npm run build
  
    - name: Publish release
      env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
          npx electron-builder --linux 
          
    - name: Package for Linux
      run: npx electron-builder --linux --publish never

    - name: Create Release Tag
      id: create_tag
      uses: actions/github-script@v6
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        script: |
          const { data } = await github.git.createTag({
            ...context.repo,
            tag: 'v${{ github.run_number }}',
            message: 'Release ${{ github.run_number }}',
            object: context.sha
          })

          return data.sha

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
      with:
        tag_name: ${{ steps.create_tag.outputs.sha }}
        release_name: Release ${{ github.run_number }}
        draft: false
        prerelease: false

    - name: Upload Linux Build 
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }} 
        asset_path: ./dist/app.AppImage
        asset_name: app-${{ github.run_number }}.AppImage
        asset_content_type: application/x-executable
