name: Build and Release

on: 
  push:
    branches:
      - main

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Install Node.js
      uses: actions/setup-node@v2
      with: 
        node-version: 14
        
    - name: Install and build
    run: |
          npm install
          npm run postinstall
          npm run build

    - name: Publish releases
        env:
          # This is used for uploading release assets to github
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npm exec electron-builder -- --publish always --win --mac --linux
